version: "3.9"

services:
  client:
    build:
      context: .
      target: client-service
    volumes:
      - ./src/client:/app/src/client:ro
    container_name: client
    ports:
      - "3007:3007"
    expose:
      - "3007"
    depends_on:
      - redis

  catalog-server:
    build:
      context: .
      target: catalog-service
    container_name: catalog-server
    ports:
      - "3005:5000"
    expose:
      - "5000"
    volumes:
      - ./src/catalog:/app/src/catalog
      - ./src/nginx:/app/src/nginx:ro
    depends_on:
      - redis

  order-server:
    build:
      context: .
      target: order-service
    volumes:
      - ./src/order:/app/src/order:ro
      - ./src/nginx:/app/src/nginx:ro
    container_name: order-server
    ports:
      - "3006:4000"
    expose:
      - "4000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - catalog-server
      - order-server
      - client
