services:
  client:
    image: client-service
    build:
      context: .
    ports:
      - "4000:4000"
      - "5000:5000"
    volumes:
      - ./src/catalog/index.js:/app/src/catalog/index.js
      - ./src/order:/app/src/order
      - ./src/client-service:/app/src/client-service
      - ./src/client-service:/app/src/client-service:ro
      - ./src/catalog/database.db:/app/src/catalog/database.db  # ✅ تعديل هنا
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
