version: "3.9"

services:
  client:
    build:
      context: .
    container_name: client
    ports:
      - "3007:3000"
    expose:
      - "3000"
    depends_on:
      - redis

  catalog-server:
    build:
      context: .
    container_name: catalog-server
    ports:
      - "3005:3000"
    expose:
      - "3000"
    depends_on:
      - redis

  order-server:
    build:
      context: .
    container_name: order-server
    ports:
      - "3006:3000"
    expose:
      - "3000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - client
      - catalog-server
      - order-server
      - redis
