
services:
  catalog:
    build: ./catalog
    ports:
      - "5001:5000"
    volumes:
      - .:/app


#  order:
#    build: ./order
#    ports:
#      - "5002:5000"
#    depends_on:
#      - catalog
