services:
  client:
    image: client-service
    build:
      context: .
    ports:
      - "4000:4000"
      - "5000:5000"
    volumes:
      - ./src/client-service:/app/src/client-service:ro
    depends_on:
      - redis
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      endpoint_mode: dnsrr

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
